export const CATEGORY_KEYWORDS: Record<string, string[]> = {
  politics: [
    "election",
    "vote",
    "voting",
    "government",
    "president",
    "congress",
    "political",
    "senate",
    "republican",
    "democrat",
    "democracy",
    "policy",
    "campaign",
    "legislature",
    "governor",
    "mayor",
    "politician",
    "cabinet",
    "parliament",
    "minister",
    "bill",
    "law",
    "constitution",
    "supreme court",
    "judicial",
    "ballot",
    "primary",
    "polls",
  ],
  business: [
    "stock",
    "market",
    "economy",
    "finance",
    "company",
    "profit",
    "revenue",
    "earnings",
    "investment",
    "corporate",
    "business",
    "trade",
    "economic",
    "financial",
    "bank",
    "industry",
    "merger",
    "acquisition",
    "startup",
    "entrepreneur",
    "CEO",
    "IPO",
    "shares",
    "dividend",
    "inflation",
    "GDP",
    "nasdaq",
    "dow jones",
    "wall street",
  ],
  technology: [
    "tech",
    "AI",
    "software",
    "digital",
    "app",
    "innovation",
    "artificial intelligence",
    "computer",
    "internet",
    "smartphone",
    "cyber",
    "data",
    "algorithm",
    "programming",
    "silicon valley",
    "blockchain",
    "cryptocurrency",
    "bitcoin",
    "cloud",
    "machine learning",
    "robot",
    "automation",
    "VR",
    "virtual reality",
    "IoT",
    "cybersecurity",
    "tech giant",
  ],
  health: [
    "medical",
    "health",
    "hospital",
    "doctor",
    "vaccine",
    "treatment",
    "medicine",
    "disease",
    "patient",
    "healthcare",
    "pharmaceutical",
    "clinical",
    "diagnosis",
    "therapy",
    "wellness",
    "epidemic",
    "pandemic",
    "virus",
    "infection",
    "surgery",
    "nurse",
    "medication",
    "FDA",
    "WHO",
    "outbreak",
    "symptoms",
    "cure",
  ],
  science: [
    "research",
    "study",
    "scientist",
    "discovery",
    "climate",
    "space",
    "experiment",
    "laboratory",
    "scientific",
    "physics",
    "chemistry",
    "biology",
    "astronomy",
    "geology",
    "academic",
    "university research",
    "NASA",
    "genome",
    "DNA",
    "evolution",
    "theory",
    "hypothesis",
    "peer review",
    "journal",
    "breakthrough",
  ],
  entertainment: [
    "movie",
    "music",
    "celebrity",
    "hollywood",
    "game",
    "show",
    "film",
    "actor",
    "actress",
    "concert",
    "album",
    "television",
    "TV",
    "streaming",
    "gaming",
    "award",
    "festival",
    "oscar",
    "grammy",
    "netflix",
    "disney",
    "studio",
    "director",
    "producer",
    "box office",
    "premiere",
    "soundtrack",
  ],
  sports: [
    "football",
    "basketball",
    "olympics",
    "team",
    "player",
    "tournament",
    "baseball",
    "soccer",
    "tennis",
    "golf",
    "championship",
    "coach",
    "game",
    "sport",
    "athletic",
    "league",
    "stadium",
    "NFL",
    "NBA",
    "MLB",
    "FIFA",
    "champion",
    "playoff",
    "season",
    "match",
    "score",
    "referee",
    "injury",
    "draft",
  ],
  environment: [
    "climate change",
    "pollution",
    "renewable",
    "carbon",
    "green",
    "environment",
    "sustainability",
    "emissions",
    "conservation",
    "wildlife",
    "ecosystem",
    "global warming",
    "recycling",
    "environmental",
    "nature",
    "solar",
    "wind power",
    "fossil fuel",
    "greenhouse gas",
    "biodiversity",
    "deforestation",
    "ocean",
    "renewable energy",
    "electric vehicle",
    "carbon footprint",
  ],
  education: [
    "school",
    "university",
    "student",
    "teacher",
    "academic",
    "college",
    "education",
    "learning",
    "classroom",
    "curriculum",
    "graduation",
    "educational",
    "scholarship",
    "degree",
    "campus",
    "professor",
    "tuition",
    "enrollment",
    "diploma",
    "exam",
    "homework",
    "semester",
    "grade",
    "principal",
    "faculty",
    "alumni",
  ],
};

export const LOCATION_VALIDATOR = {
  invalidTerms: ["News", "Reuters", "AP", "CNN", "BBC", "Today", "Police"],
  dayNames: [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday",
  ],
  months: [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ],
};

export const MAP_LAYERS = {
  openstreetmap: {
    name: "Street Map",
    url: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
    attribution:
      '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
  },
  satellite: {
    name: "Satellite",
    url: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
    attribution:
      "Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community",
  },
  terrain: {
    name: "Terrain",
    url: "https://stamen-tiles.a.ssl.fastly.net/terrain/{z}/{x}/{y}.png",
    attribution:
      'Map tiles by <a href="http://stamen.com">Stamen Design</a>, under <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a>. Data by <a href="http://openstreetmap.org">OpenStreetMap</a>, under <a href="http://www.openstreetmap.org/copyright">ODbL</a>.',
  },
  dark: {
    name: "Dark Mode",
    url: "https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",
    attribution:
      '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
  },
  light: {
    name: "Light Mode",
    url: "https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png",
    attribution:
      '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
  },
} as const;
