import {
  Contrast,
  Droplets,
  Globe,
  Heart,
  Map,
  Moon,
  Mountain,
  Satellite,
  Sun,
} from "lucide-react";
import { createElement } from "react";

export const CATEGORY_KEYWORDS: Record<string, string[]> = {
  politics: [
    "election",
    "vote",
    "voting",
    "government",
    "president",
    "congress",
    "political",
    "senate",
    "republican",
    "democrat",
    "democracy",
    "policy",
    "campaign",
    "legislature",
    "governor",
    "mayor",
    "politician",
    "cabinet",
    "parliament",
    "minister",
    "bill",
    "law",
    "constitution",
    "supreme court",
    "judicial",
    "ballot",
    "primary",
    "polls",
  ],
  business: [
    "stock",
    "market",
    "economy",
    "finance",
    "company",
    "profit",
    "revenue",
    "earnings",
    "investment",
    "corporate",
    "business",
    "trade",
    "economic",
    "financial",
    "bank",
    "industry",
    "merger",
    "acquisition",
    "startup",
    "entrepreneur",
    "CEO",
    "IPO",
    "shares",
    "dividend",
    "inflation",
    "GDP",
    "nasdaq",
    "dow jones",
    "wall street",
  ],
  technology: [
    "tech",
    "AI",
    "software",
    "digital",
    "app",
    "innovation",
    "artificial intelligence",
    "computer",
    "internet",
    "smartphone",
    "cyber",
    "data",
    "algorithm",
    "programming",
    "silicon valley",
    "blockchain",
    "cryptocurrency",
    "bitcoin",
    "cloud",
    "machine learning",
    "robot",
    "automation",
    "VR",
    "virtual reality",
    "IoT",
    "cybersecurity",
    "tech giant",
  ],
  health: [
    "medical",
    "health",
    "hospital",
    "doctor",
    "vaccine",
    "treatment",
    "medicine",
    "disease",
    "patient",
    "healthcare",
    "pharmaceutical",
    "clinical",
    "diagnosis",
    "therapy",
    "wellness",
    "epidemic",
    "pandemic",
    "virus",
    "infection",
    "surgery",
    "nurse",
    "medication",
    "FDA",
    "WHO",
    "outbreak",
    "symptoms",
    "cure",
  ],
  science: [
    "research",
    "study",
    "scientist",
    "discovery",
    "climate",
    "space",
    "experiment",
    "laboratory",
    "scientific",
    "physics",
    "chemistry",
    "biology",
    "astronomy",
    "geology",
    "academic",
    "university research",
    "NASA",
    "genome",
    "DNA",
    "evolution",
    "theory",
    "hypothesis",
    "peer review",
    "journal",
    "breakthrough",
  ],
  entertainment: [
    "movie",
    "music",
    "celebrity",
    "hollywood",
    "game",
    "show",
    "film",
    "actor",
    "actress",
    "concert",
    "album",
    "television",
    "TV",
    "streaming",
    "gaming",
    "award",
    "festival",
    "oscar",
    "grammy",
    "netflix",
    "disney",
    "studio",
    "director",
    "producer",
    "box office",
    "premiere",
    "soundtrack",
  ],
  sports: [
    "football",
    "basketball",
    "olympics",
    "team",
    "player",
    "tournament",
    "baseball",
    "soccer",
    "tennis",
    "golf",
    "championship",
    "coach",
    "game",
    "sport",
    "athletic",
    "league",
    "stadium",
    "NFL",
    "NBA",
    "MLB",
    "FIFA",
    "champion",
    "playoff",
    "season",
    "match",
    "score",
    "referee",
    "injury",
    "draft",
  ],
  environment: [
    "climate change",
    "pollution",
    "renewable",
    "carbon",
    "green",
    "environment",
    "sustainability",
    "emissions",
    "conservation",
    "wildlife",
    "ecosystem",
    "global warming",
    "recycling",
    "environmental",
    "nature",
    "solar",
    "wind power",
    "fossil fuel",
    "greenhouse gas",
    "biodiversity",
    "deforestation",
    "ocean",
    "renewable energy",
    "electric vehicle",
    "carbon footprint",
  ],
  education: [
    "school",
    "university",
    "student",
    "teacher",
    "academic",
    "college",
    "education",
    "learning",
    "classroom",
    "curriculum",
    "graduation",
    "educational",
    "scholarship",
    "degree",
    "campus",
    "professor",
    "tuition",
    "enrollment",
    "diploma",
    "exam",
    "homework",
    "semester",
    "grade",
    "principal",
    "faculty",
    "alumni",
  ],
};

export const LOCATION_VALIDATOR = {
  invalidTerms: ["News", "Reuters", "AP", "CNN", "BBC", "Today", "Police"],
  dayNames: [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday",
  ],
  months: [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ],
};

export const MAP_LAYERS = {
  // Core Navigation
  street: {
    name: "Street",
    url: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
    colors: "text-blue-600 bg-blue-50 border-blue-200",
    icon: createElement(Map, { className: "h-4 w-4" }),
  },
  light: {
    name: "Light",
    url: "https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png",
    colors: "text-amber-600 bg-amber-50 border-amber-200",
    icon: createElement(Sun, { className: "h-4 w-4" }),
  },
  dark: {
    name: "Dark",
    url: "https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",
    colors: "text-slate-600 bg-slate-50 border-slate-200",
    icon: createElement(Moon, { className: "h-4 w-4" }),
  },

  // Imagery & Terrain
  satellite: {
    name: "Satellite",
    url: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
    colors: "text-green-600 bg-green-50 border-green-200",
    icon: createElement(Satellite, { className: "h-4 w-4" }),
  },
  terrain: {
    name: "Terrain",
    url: "https://tile.opentopomap.org/{z}/{x}/{y}.png",
    colors: "text-orange-600 bg-orange-50 border-orange-200",
    icon: createElement(Mountain, { className: "h-4 w-4" }),
  },

  // Specialized
  humanitarian: {
    name: "Crisis",
    url: "https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png",
    colors: "text-red-600 bg-red-50 border-red-200",
    icon: createElement(Heart, { className: "h-4 w-4" }),
  },

  // Artistic
  watercolor: {
    name: "Artistic",
    url: "https://tiles.stadiamaps.com/tiles/stamen_watercolor/{z}/{x}/{y}.jpg",
    colors: "text-teal-600 bg-teal-50 border-teal-200",
    icon: createElement(Droplets, { className: "h-4 w-4" }),
  },
  toner: {
    name: "Contrast",
    url: "https://tiles.stadiamaps.com/tiles/stamen_toner/{z}/{x}/{y}{r}.png",
    colors: "text-gray-600 bg-gray-50 border-gray-200",
    icon: createElement(Contrast, { className: "h-4 w-4" }),
  },
  colorful: {
    name: "Vibrant",
    url: "https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png",
    colors: "text-emerald-600 bg-emerald-50 border-emerald-200",
    icon: createElement(Globe, { className: "h-4 w-4" }),
  },
} as const;

export type LayerKey = keyof typeof MAP_LAYERS;
