export const countries = [
  { name: "Afghanistan", flag: "🇦🇫", value: "AF" },
  { name: "Angola", flag: "🇦🇴", value: "AO" },
  { name: "Albania", flag: "🇦🇱", value: "AL" },
  { name: "Andorra", flag: "🇦🇩", value: "AD" },
  { name: "United Arab Emirates", flag: "🇦🇪", value: "AE" },
  { name: "Argentina", flag: "🇦🇷", value: "AR" },
  { name: "Armenia", flag: "🇦🇲", value: "AM" },
  { name: "Antigua and Barbuda", flag: "🇦🇬", value: "AG" },
  { name: "Australia", flag: "🇦🇺", value: "AU" },
  { name: "Austria", flag: "🇦🇹", value: "AT" },
  { name: "Azerbaijan", flag: "🇦🇿", value: "AZ" },
  { name: "Burundi", flag: "🇧🇮", value: "BI" },
  { name: "Belgium", flag: "🇧🇪", value: "BE" },
  { name: "Benin", flag: "🇧🇯", value: "BJ" },
  { name: "Burkina Faso", flag: "🇧🇫", value: "BF" },
  { name: "Bangladesh", flag: "🇧🇩", value: "BD" },
  { name: "Bulgaria", flag: "🇧🇬", value: "BG" },
  { name: "Bahrain", flag: "🇧🇭", value: "BH" },
  { name: "Bahamas", flag: "🇧🇸", value: "BS" },
  { name: "Bosnia and Herzegovina", flag: "🇧🇦", value: "BA" },
  { name: "Belarus", flag: "🇧🇾", value: "BY" },
  { name: "Belize", flag: "🇧🇿", value: "BZ" },
  { name: "Bolivia", flag: "🇧🇴", value: "BO" },
  { name: "Brazil", flag: "🇧🇷", value: "BR" },
  { name: "Barbados", flag: "🇧🇧", value: "BB" },
  { name: "Brunei", flag: "🇧🇳", value: "BN" },
  { name: "Bhutan", flag: "🇧🇹", value: "BT" },
  { name: "Botswana", flag: "🇧🇼", value: "BW" },
  { name: "Central African Republic", flag: "🇨🇫", value: "CF" },
  { name: "Canada", flag: "🇨🇦", value: "CA" },
  { name: "Switzerland", flag: "🇨🇭", value: "CH" },
  { name: "Chile", flag: "🇨🇱", value: "CL" },
  { name: "China", flag: "🇨🇳", value: "CN" },
  { name: "Ivory Coast", flag: "🇨🇮", value: "CI" },
  { name: "Cameroon", flag: "🇨🇲", value: "CM" },
  { name: "DR Congo", flag: "🇨🇩", value: "CD" },
  { name: "Republic of the Congo", flag: "🇨🇬", value: "CG" },
  { name: "Colombia", flag: "🇨🇴", value: "CO" },
  { name: "Comoros", flag: "🇰🇲", value: "KM" },
  { name: "Cape Verde", flag: "🇨🇻", value: "CV" },
  { name: "Costa Rica", flag: "🇨🇷", value: "CR" },
  { name: "Cuba", flag: "🇨🇺", value: "CU" },
  { name: "Cyprus", flag: "🇨🇾", value: "CY" },
  { name: "Czechia", flag: "🇨🇿", value: "CZ" },
  { name: "Germany", flag: "🇩🇪", value: "DE" },
  { name: "Djibouti", flag: "🇩🇯", value: "DJ" },
  { name: "Dominica", flag: "🇩🇲", value: "DM" },
  { name: "Denmark", flag: "🇩🇰", value: "DK" },
  { name: "Dominican Republic", flag: "🇩🇴", value: "DO" },
  { name: "Algeria", flag: "🇩🇿", value: "DZ" },
  { name: "Ecuador", flag: "🇪🇨", value: "EC" },
  { name: "Egypt", flag: "🇪🇬", value: "EG" },
  { name: "Eritrea", flag: "🇪🇷", value: "ER" },
  { name: "Spain", flag: "🇪🇸", value: "ES" },
  { name: "Estonia", flag: "🇪🇪", value: "EE" },
  { name: "Ethiopia", flag: "🇪🇹", value: "ET" },
  { name: "Finland", flag: "🇫🇮", value: "FI" },
  { name: "Fiji", flag: "🇫🇯", value: "FJ" },
  { name: "France", flag: "🇫🇷", value: "FR" },
  { name: "Micronesia", flag: "🇫🇲", value: "FM" },
  { name: "Gabon", flag: "🇬🇦", value: "GA" },
  { name: "United Kingdom", flag: "🇬🇧", value: "GB" },
  { name: "Georgia", flag: "🇬🇪", value: "GE" },
  { name: "Ghana", flag: "🇬🇭", value: "GH" },
  { name: "Guinea", flag: "🇬🇳", value: "GN" },
  { name: "Gambia", flag: "🇬🇲", value: "GM" },
  { name: "Guinea-Bissau", flag: "🇬🇼", value: "GW" },
  { name: "Equatorial Guinea", flag: "🇬🇶", value: "GQ" },
  { name: "Greece", flag: "🇬🇷", value: "GR" },
  { name: "Grenada", flag: "🇬🇩", value: "GD" },
  { name: "Guatemala", flag: "🇬🇹", value: "GT" },
  { name: "Guyana", flag: "🇬🇾", value: "GY" },
  { name: "Honduras", flag: "🇭🇳", value: "HN" },
  { name: "Croatia", flag: "🇭🇷", value: "HR" },
  { name: "Haiti", flag: "🇭🇹", value: "HT" },
  { name: "Hungary", flag: "🇭🇺", value: "HU" },
  { name: "Indonesia", flag: "🇮🇩", value: "ID" },
  { name: "India", flag: "🇮🇳", value: "IN" },
  { name: "Ireland", flag: "🇮🇪", value: "IE" },
  { name: "Iran", flag: "🇮🇷", value: "IR" },
  { name: "Iraq", flag: "🇮🇶", value: "IQ" },
  { name: "Iceland", flag: "🇮🇸", value: "IS" },
  { name: "Israel", flag: "🇮🇱", value: "IL" },
  { name: "Italy", flag: "🇮🇹", value: "IT" },
  { name: "Jamaica", flag: "🇯🇲", value: "JM" },
  { name: "Jordan", flag: "🇯🇴", value: "JO" },
  { name: "Japan", flag: "🇯🇵", value: "JP" },
  { name: "Kazakhstan", flag: "🇰🇿", value: "KZ" },
  { name: "Kenya", flag: "🇰🇪", value: "KE" },
  { name: "Kyrgyzstan", flag: "🇰🇬", value: "KG" },
  { name: "Cambodia", flag: "🇰🇭", value: "KH" },
  { name: "Kiribati", flag: "🇰🇮", value: "KI" },
  { name: "Saint Kitts and Nevis", flag: "🇰🇳", value: "KN" },
  { name: "South Korea", flag: "🇰🇷", value: "KR" },
  { name: "Kuwait", flag: "🇰🇼", value: "KW" },
  { name: "Laos", flag: "🇱🇦", value: "LA" },
  { name: "Lebanon", flag: "🇱🇧", value: "LB" },
  { name: "Liberia", flag: "🇱🇷", value: "LR" },
  { name: "Libya", flag: "🇱🇾", value: "LY" },
  { name: "Saint Lucia", flag: "🇱🇨", value: "LC" },
  { name: "Liechtenstein", flag: "🇱🇮", value: "LI" },
  { name: "Sri Lanka", flag: "🇱🇰", value: "LK" },
  { name: "Lesotho", flag: "🇱🇸", value: "LS" },
  { name: "Lithuania", flag: "🇱🇹", value: "LT" },
  { name: "Luxembourg", flag: "🇱🇺", value: "LU" },
  { name: "Latvia", flag: "🇱🇻", value: "LV" },
  { name: "Morocco", flag: "🇲🇦", value: "MA" },
  { name: "Monaco", flag: "🇲🇨", value: "MC" },
  { name: "Moldova", flag: "🇲🇩", value: "MD" },
  { name: "Madagascar", flag: "🇲🇬", value: "MG" },
  { name: "Maldives", flag: "🇲🇻", value: "MV" },
  { name: "Mexico", flag: "🇲🇽", value: "MX" },
  { name: "Marshall Islands", flag: "🇲🇭", value: "MH" },
  { name: "Macedonia", flag: "🇲🇰", value: "MK" },
  { name: "Mali", flag: "🇲🇱", value: "ML" },
  { name: "Malta", flag: "🇲🇹", value: "MT" },
  { name: "Myanmar", flag: "🇲🇲", value: "MM" },
  { name: "Montenegro", flag: "🇲🇪", value: "ME" },
  { name: "Mongolia", flag: "🇲🇳", value: "MN" },
  { name: "Mozambique", flag: "🇲🇿", value: "MZ" },
  { name: "Mauritania", flag: "🇲🇷", value: "MR" },
  { name: "Mauritius", flag: "🇲🇺", value: "MU" },
  { name: "Malawi", flag: "🇲🇼", value: "MW" },
  { name: "Malaysia", flag: "🇲🇾", value: "MY" },
  { name: "Namibia", flag: "🇳🇦", value: "NA" },
  { name: "Niger", flag: "🇳🇪", value: "NE" },
  { name: "Nigeria", flag: "🇳🇬", value: "NG" },
  { name: "Nicaragua", flag: "🇳🇮", value: "NI" },
  { name: "Netherlands", flag: "🇳🇱", value: "NL" },
  { name: "Norway", flag: "🇳🇴", value: "NO" },
  { name: "Nepal", flag: "🇳🇵", value: "NP" },
  { name: "Nauru", flag: "🇳🇷", value: "NR" },
  { name: "New Zealand", flag: "🇳🇿", value: "NZ" },
  { name: "Oman", flag: "🇴🇲", value: "OM" },
  { name: "Pakistan", flag: "🇵🇰", value: "PK" },
  { name: "Panama", flag: "🇵🇦", value: "PA" },
  { name: "Peru", flag: "🇵🇪", value: "PE" },
  { name: "Philippines", flag: "🇵🇭", value: "PH" },
  { name: "Palau", flag: "🇵🇼", value: "PW" },
  { name: "Papua New Guinea", flag: "🇵🇬", value: "PG" },
  { name: "Poland", flag: "🇵🇱", value: "PL" },
  { name: "North Korea", flag: "🇰🇵", value: "KP" },
  { name: "Portugal", flag: "🇵🇹", value: "PT" },
  { name: "Paraguay", flag: "🇵🇾", value: "PY" },
  { name: "Qatar", flag: "🇶🇦", value: "QA" },
  { name: "Romania", flag: "🇷🇴", value: "RO" },
  { name: "Russia", flag: "🇷🇺", value: "RU" },
  { name: "Rwanda", flag: "🇷🇼", value: "RW" },
  { name: "Saudi Arabia", flag: "🇸🇦", value: "SA" },
  { name: "Sudan", flag: "🇸🇩", value: "SD" },
  { name: "Senegal", flag: "🇸🇳", value: "SN" },
  { name: "Singapore", flag: "🇸🇬", value: "SG" },
  { name: "Solomon Islands", flag: "🇸🇧", value: "SB" },
  { name: "Sierra Leone", flag: "🇸🇱", value: "SL" },
  { name: "El Salvador", flag: "🇸🇻", value: "SV" },
  { name: "San Marino", flag: "🇸🇲", value: "SM" },
  { name: "Somalia", flag: "🇸🇴", value: "SO" },
  { name: "Serbia", flag: "🇷🇸", value: "RS" },
  { name: "South Sudan", flag: "🇸🇸", value: "SS" },
  { name: "São Tomé and Príncipe", flag: "🇸🇹", value: "ST" },
  { name: "Suriname", flag: "🇸🇷", value: "SR" },
  { name: "Slovakia", flag: "🇸🇰", value: "SK" },
  { name: "Slovenia", flag: "🇸🇮", value: "SI" },
  { name: "Sweden", flag: "🇸🇪", value: "SE" },
  { name: "Swaziland", flag: "🇸🇿", value: "SZ" },
  { name: "Seychelles", flag: "🇸🇨", value: "SC" },
  { name: "Syria", flag: "🇸🇾", value: "SY" },
  { name: "Chad", flag: "🇹🇩", value: "TD" },
  { name: "Togo", flag: "🇹🇬", value: "TG" },
  { name: "Thailand", flag: "🇹🇭", value: "TH" },
  { name: "Tajikistan", flag: "🇹🇯", value: "TJ" },
  { name: "Turkmenistan", flag: "🇹🇲", value: "TM" },
  { name: "Timor-Leste", flag: "🇹🇱", value: "TL" },
  { name: "Tonga", flag: "🇹🇴", value: "TO" },
  { name: "Trinidad and Tobago", flag: "🇹🇹", value: "TT" },
  { name: "Tunisia", flag: "🇹🇳", value: "TN" },
  { name: "Turkey", flag: "🇹🇷", value: "TR" },
  { name: "Tuvalu", flag: "🇹🇻", value: "TV" },
  { name: "Tanzania", flag: "🇹🇿", value: "TZ" },
  { name: "Uganda", flag: "🇺🇬", value: "UG" },
  { name: "Ukraine", flag: "🇺🇦", value: "UA" },
  { name: "Uruguay", flag: "🇺🇾", value: "UY" },
  { name: "United States", flag: "🇺🇸", value: "US" },
  { name: "Uzbekistan", flag: "🇺🇿", value: "UZ" },
  { name: "Vatican City", flag: "🇻🇦", value: "VA" },
  { name: "Saint Vincent and the Grenadines", flag: "🇻🇨", value: "VC" },
  { name: "Venezuela", flag: "🇻🇪", value: "VE" },
  { name: "Vietnam", flag: "🇻🇳", value: "VN" },
  { name: "Vanuatu", flag: "🇻🇺", value: "VU" },
  { name: "Samoa", flag: "🇼🇸", value: "WS" },
  { name: "Yemen", flag: "🇾🇪", value: "YE" },
  { name: "South Africa", flag: "🇿🇦", value: "ZA" },
  { name: "Zambia", flag: "🇿🇲", value: "ZM" },
  { name: "Zimbabwe", flag: "🇿🇼", value: "ZW" },
];

export const timezones = [
  { name: "UTC-12:00 (Baker Island)", value: "UTC-12:00", flag: "🕐" },
  { name: "UTC-11:00 (American Samoa)", value: "UTC-11:00", flag: "🕐" },
  { name: "UTC-10:00 (Hawaii)", value: "UTC-10:00", flag: "🕐" },
  { name: "UTC-09:00 (Alaska)", value: "UTC-09:00", flag: "🕐" },
  { name: "UTC-08:00 (Pacific)", value: "UTC-08:00", flag: "🕐" },
  { name: "UTC-07:00 (Mountain)", value: "UTC-07:00", flag: "🕐" },
  { name: "UTC-06:00 (Central)", value: "UTC-06:00", flag: "🕐" },
  { name: "UTC-05:00 (Eastern)", value: "UTC-05:00", flag: "🕐" },
  { name: "UTC-04:00 (Atlantic)", value: "UTC-04:00", flag: "🕐" },
  { name: "UTC-03:00 (Argentina)", value: "UTC-03:00", flag: "🕐" },
  { name: "UTC-02:00 (Mid-Atlantic)", value: "UTC-02:00", flag: "🕐" },
  { name: "UTC-01:00 (Azores)", value: "UTC-01:00", flag: "🕐" },
  { name: "UTC+00:00 (London)", value: "UTC+00:00", flag: "🕐" },
  { name: "UTC+01:00 (Berlin)", value: "UTC+01:00", flag: "🕐" },
  { name: "UTC+02:00 (Cairo)", value: "UTC+02:00", flag: "🕐" },
  { name: "UTC+03:00 (Moscow)", value: "UTC+03:00", flag: "🕐" },
  { name: "UTC+04:00 (Dubai)", value: "UTC+04:00", flag: "🕐" },
  { name: "UTC+05:00 (Karachi)", value: "UTC+05:00", flag: "🕐" },
  { name: "UTC+05:30 (Mumbai)", value: "UTC+05:30", flag: "🕐" },
  { name: "UTC+06:00 (Dhaka)", value: "UTC+06:00", flag: "🕐" },
  { name: "UTC+07:00 (Bangkok)", value: "UTC+07:00", flag: "🕐" },
  { name: "UTC+08:00 (Beijing)", value: "UTC+08:00", flag: "🕐" },
  { name: "UTC+09:00 (Tokyo)", value: "UTC+09:00", flag: "🕐" },
  { name: "UTC+10:00 (Sydney)", value: "UTC+10:00", flag: "🕐" },
  { name: "UTC+11:00 (Solomon Islands)", value: "UTC+11:00", flag: "🕐" },
  { name: "UTC+12:00 (New Zealand)", value: "UTC+12:00", flag: "🕐" },
];

export const languages = [
  { name: "Afrikaans", flag: "🇿🇦", value: "AF" },
  { name: "Albanian", flag: "🇦🇱", value: "SQ" },
  { name: "Amharic", flag: "🇪🇹", value: "AM" },
  { name: "Arabic", flag: "🇸🇦", value: "AR" },
  { name: "Armenian", flag: "🇦🇲", value: "HY" },
  { name: "Assamese", flag: "🇮🇳", value: "AS" },
  { name: "Aymara", flag: "🇧🇴", value: "AY" },
  { name: "Azerbaijani", flag: "🇦🇿", value: "AZ" },
  { name: "Bengali", flag: "🇧🇩", value: "BN" },
  { name: "Bhojpuri", flag: "🇮🇳", value: "BH" },
  { name: "Bosnian", flag: "🇧🇦", value: "BS" },
  { name: "Bulgarian", flag: "🇧🇬", value: "BG" },
  { name: "Catalan", flag: "🇪🇸", value: "CA" },
  { name: "Cebuano", flag: "🇵🇭", value: "CEB" },
  { name: "Chewa", flag: "🇲🇼", value: "NY" },
  { name: "Chinese (Simplified)", flag: "🇨🇳", value: "ZH" },
  { name: "Chinese (Traditional)", flag: "🇨🇳", value: "ZH-TW" },
  { name: "Corsican", flag: "🇫🇷", value: "CO" },
  { name: "Croatian", flag: "🇭🇷", value: "HR" },
  { name: "Czech", flag: "🇨🇿", value: "CS" },
  { name: "Danish", flag: "🇩🇰", value: "DA" },
  { name: "Dhivehi", flag: "🇲🇻", value: "DV" },
  { name: "Dutch", flag: "🇳🇱", value: "NL" },
  { name: "English", flag: "🇬🇧", value: "EN" },
  { name: "Esperanto", flag: "🌐", value: "EO" },
  { name: "Estonian", flag: "🇪🇪", value: "ET" },
  { name: "Ewe", flag: "🇬🇭", value: "EE" },
  { name: "Filipino", flag: "🇵🇭", value: "TL" },
  { name: "Finnish", flag: "🇫🇮", value: "FI" },
  { name: "French", flag: "🇫🇷", value: "FR" },
  { name: "Frisian", flag: "🇳🇱", value: "FY" },
  { name: "Galician", flag: "🇪🇸", value: "GL" },
  { name: "Georgian", flag: "🇬🇪", value: "KA" },
  { name: "German", flag: "🇩🇪", value: "DE" },
  { name: "Greek", flag: "🇬🇷", value: "EL" },
  { name: "Gujarati", flag: "🇮🇳", value: "GU" },
  { name: "Haitian Creole", flag: "🇭🇹", value: "HT" },
  { name: "Hausa", flag: "🇳🇬", value: "HA" },
  { name: "Hawaiian", flag: "🇺🇸", value: "HAW" },
  { name: "Hebrew", flag: "🇮🇱", value: "HE" },
  { name: "Hindi", flag: "🇮🇳", value: "HI" },
  { name: "Hungarian", flag: "🇭🇺", value: "HU" },
  { name: "Icelandic", flag: "🇮🇸", value: "IS" },
  { name: "Igbo", flag: "🇳🇬", value: "IG" },
  { name: "Ilocano", flag: "🇵🇭", value: "ILO" },
  { name: "Indonesian", flag: "🇮🇩", value: "ID" },
  { name: "Irish", flag: "🇮🇪", value: "GA" },
  { name: "Italian", flag: "🇮🇹", value: "IT" },
  { name: "Japanese", flag: "🇯🇵", value: "JA" },
  { name: "Javanese", flag: "🇮🇩", value: "JV" },
  { name: "Kannada", flag: "🇮🇳", value: "KN" },
  { name: "Kazakh", flag: "🇰🇿", value: "KK" },
  { name: "Khmer", flag: "🇰🇭", value: "KM" },
  { name: "Kinyarwanda", flag: "🇷🇼", value: "RW" },
  { name: "Konkani", flag: "🇮🇳", value: "KOK" },
  { name: "Korean", flag: "🇰🇷", value: "KO" },
  { name: "Kurdish (Kurmanji)", flag: "🇹🇷", value: "KU" },
  { name: "Kurdish (Sorani)", flag: "🇮🇶", value: "CKB" },
  { name: "Kyrgyz", flag: "🇰🇬", value: "KY" },
  { name: "Lao", flag: "🇱🇦", value: "LO" },
  { name: "Latin", flag: "🌐", value: "LA" },
  { name: "Latvian", flag: "🇱🇻", value: "LV" },
  { name: "Lingala", flag: "🇨🇩", value: "LN" },
  { name: "Lithuanian", flag: "🇱🇹", value: "LT" },
  { name: "Luganda", flag: "🇺🇬", value: "LG" },
  { name: "Luxembourgish", flag: "🇱🇺", value: "LB" },
  { name: "Macedonian", flag: "🇲🇰", value: "MK" },
  { name: "Maithili", flag: "🇮🇳", value: "MAI" },
  { name: "Malagasy", flag: "🇲🇬", value: "MG" },
  { name: "Malay", flag: "🇲🇾", value: "MS" },
  { name: "Malayalam", flag: "🇮🇳", value: "ML" },
  { name: "Maltese", flag: "🇲🇹", value: "MT" },
  { name: "Maori", flag: "🇳🇿", value: "MI" },
  { name: "Marathi", flag: "🇮🇳", value: "MR" },
  { name: "Meiteilon (Manipuri)", flag: "🇮🇳", value: "MNI" },
  { name: "Mongolian", flag: "🇲🇳", value: "MN" },
  { name: "Myanmar (Burmese)", flag: "🇲🇲", value: "MY" },
  { name: "Nepali", flag: "🇳🇵", value: "NE" },
  { name: "Norwegian", flag: "🇳🇴", value: "NO" },
  { name: "Odia (Oriya)", flag: "🇮🇳", value: "OR" },
  { name: "Oromo", flag: "🇪🇹", value: "OM" },
  { name: "Pashto", flag: "🇦🇫", value: "PS" },
  { name: "Persian", flag: "🇮🇷", value: "FA" },
  { name: "Polish", flag: "🇵🇱", value: "PL" },
  { name: "Portuguese", flag: "🇵🇹", value: "PT" },
  { name: "Punjabi", flag: "🇮🇳", value: "PA" },
  { name: "Quechua", flag: "🇵🇪", value: "QU" },
  { name: "Romanian", flag: "🇷🇴", value: "RO" },
  { name: "Russian", flag: "🇷🇺", value: "RU" },
  { name: "Samoan", flag: "🇼🇸", value: "SM" },
  { name: "Sanskrit", flag: "🇮🇳", value: "SA" },
  { name: "Scots Gaelic", flag: "🇬🇧", value: "GD" },
  { name: "Sepedi", flag: "🇿🇦", value: "NSP" },
  { name: "Serbian", flag: "🇷🇸", value: "SR" },
  { name: "Sesotho", flag: "🇿🇦", value: "ST" },
  { name: "Shona", flag: "🇿🇼", value: "SN" },
  { name: "Sindhi", flag: "🇵🇰", value: "SD" },
  { name: "Sinhala", flag: "🇱🇰", value: "SI" },
  { name: "Slovak", flag: "🇸🇰", value: "SK" },
  { name: "Slovenian", flag: "🇸🇮", value: "SL" },
  { name: "Somali", flag: "🇸🇴", value: "SO" },
  { name: "Spanish", flag: "🇪🇸", value: "ES" },
  { name: "Sundanese", flag: "🇮🇩", value: "SU" },
  { name: "Swahili", flag: "🇹🇿", value: "SW" },
  { name: "Swedish", flag: "🇸🇪", value: "SV" },
  { name: "Tajik", flag: "🇹🇯", value: "TG" },
  { name: "Tamil", flag: "🇮🇳", value: "TA" },
  { name: "Tatar", flag: "🇷🇺", value: "TT" },
  { name: "Telugu", flag: "🇮🇳", value: "TE" },
  { name: "Thai", flag: "🇹🇭", value: "TH" },
  { name: "Tigrinya", flag: "🇪🇷", value: "TI" },
  { name: "Tsonga", flag: "🇿🇦", value: "TS" },
  { name: "Turkish", flag: "🇹🇷", value: "TR" },
  { name: "Turkmen", flag: "🇹🇲", value: "TK" },
  { name: "Twi", flag: "🇬🇭", value: "TW" },
  { name: "Ukrainian", flag: "🇺🇦", value: "UK" },
  { name: "Urdu", flag: "🇵🇰", value: "UR" },
  { name: "Uyghur", flag: "🇨🇳", value: "UG" },
  { name: "Uzbek", flag: "🇺🇿", value: "UZ" },
  { name: "Vietnamese", flag: "🇻🇳", value: "VI" },
  { name: "Welsh", flag: "🇬🇧", value: "CY" },
  { name: "Xhosa", flag: "🇿🇦", value: "XH" },
  { name: "Yiddish", flag: "🇮🇱", value: "YI" },
  { name: "Yoruba", flag: "🇳🇬", value: "YO" },
  { name: "Zulu", flag: "🇿🇦", value: "ZU" },
];
