export const countries = [
  { name: "Afghanistan", code: "AF", flag: "🇦🇫" },
  { name: "Åland Islands", code: "AX", flag: "🇦🇽" },
  { name: "Albania", code: "AL", flag: "🇦🇱" },
  { name: "Algeria", code: "DZ", flag: "🇩🇿" },
  { name: "American Samoa", code: "AS", flag: "🇦🇸" },
  { name: "Andorra", code: "AD", flag: "🇦🇩" },
  { name: "Angola", code: "AO", flag: "🇦🇴" },
  { name: "Anguilla", code: "AI", flag: "🇦🇮" },
  { name: "Antarctica", code: "AQ", flag: "🇦🇶" },
  { name: "Antigua and Barbuda", code: "AG", flag: "🇦🇬" },
  { name: "Argentina", code: "AR", flag: "🇦🇷" },
  { name: "Armenia", code: "AM", flag: "🇦🇲" },
  { name: "Aruba", code: "AW", flag: "🇦🇼" },
  { name: "Australia", code: "AU", flag: "🇦🇺" },
  { name: "Austria", code: "AT", flag: "🇦🇹" },
  { name: "Azerbaijan", code: "AZ", flag: "🇦🇿" },
  { name: "Bahamas", code: "BS", flag: "🇧🇸" },
  { name: "Bahrain", code: "BH", flag: "🇧🇭" },
  { name: "Bangladesh", code: "BD", flag: "🇧🇩" },
  { name: "Barbados", code: "BB", flag: "🇧🇧" },
  { name: "Belarus", code: "BY", flag: "🇧🇾" },
  { name: "Belgium", code: "BE", flag: "🇧🇪" },
  { name: "Belize", code: "BZ", flag: "🇧🇿" },
  { name: "Benin", code: "BJ", flag: "🇧🇯" },
  { name: "Bermuda", code: "BM", flag: "🇧🇲" },
  { name: "Bhutan", code: "BT", flag: "🇧🇹" },
  { name: "Bolivia", code: "BO", flag: "🇧🇴" },
  { name: "Bonaire, Sint Eustatius and Saba", code: "BQ", flag: "🇧🇶" },
  { name: "Bosnia and Herzegovina", code: "BA", flag: "🇧🇦" },
  { name: "Botswana", code: "BW", flag: "🇧🇼" },
  { name: "Bouvet Island", code: "BV", flag: "🇧🇻" },
  { name: "Brazil", code: "BR", flag: "🇧🇷" },
  { name: "British Indian Ocean Territory", code: "IO", flag: "🇮🇴" },
  { name: "British Virgin Islands", code: "VG", flag: "🇻🇬" },
  { name: "Brunei Darussalam", code: "BN", flag: "🇧🇳" },
  { name: "Bulgaria", code: "BG", flag: "🇧🇬" },
  { name: "Burkina Faso", code: "BF", flag: "🇧🇫" },
  { name: "Burundi", code: "BI", flag: "🇧🇮" },
  { name: "Cambodia", code: "KH", flag: "🇰🇭" },
  { name: "Cameroon", code: "CM", flag: "🇨🇲" },
  { name: "Canada", code: "CA", flag: "🇨🇦" },
  { name: "Cape Verde", code: "CV", flag: "🇨🇻" },
  { name: "Cayman Islands", code: "KY", flag: "🇰🇾" },
  { name: "Central African Republic", code: "CF", flag: "🇨🇫" },
  { name: "Chad", code: "TD", flag: "🇹🇩" },
  { name: "Chile", code: "CL", flag: "🇨🇱" },
  { name: "China", code: "CN", flag: "🇨🇳" },
  { name: "Christmas Island", code: "CX", flag: "🇨🇽" },
  { name: "Cocos (Keeling) Islands", code: "CC", flag: "🇨🇨" },
  { name: "Colombia", code: "CO", flag: "🇨🇴" },
  { name: "Comoros", code: "KM", flag: "🇰🇲" },
  { name: "Congo", code: "CG", flag: "🇨🇬" },
  { name: "Congo, Democratic Republic of the", code: "CD", flag: "🇨🇩" },
  { name: "Cook Islands", code: "CK", flag: "🇨🇰" },
  { name: "Costa Rica", code: "CR", flag: "🇨🇷" },
  { name: "Croatia", code: "HR", flag: "🇭🇷" },
  { name: "Cuba", code: "CU", flag: "🇨🇺" },
  { name: "Curaçao", code: "CW", flag: "🇨🇼" },
  { name: "Cyprus", code: "CY", flag: "🇨🇾" },
  { name: "Czech Republic", code: "CZ", flag: "🇨🇿" },
  { name: "Côte d'Ivoire", code: "CI", flag: "🇨🇮" },
  { name: "Denmark", code: "DK", flag: "🇩🇰" },
  { name: "Djibouti", code: "DJ", flag: "🇩🇯" },
  { name: "Dominica", code: "DM", flag: "🇩🇲" },
  { name: "Dominican Republic", code: "DO", flag: "🇩🇴" },
  { name: "Ecuador", code: "EC", flag: "🇪🇨" },
  { name: "Egypt", code: "EG", flag: "🇪🇬" },
  { name: "El Salvador", code: "SV", flag: "🇸🇻" },
  { name: "Equatorial Guinea", code: "GQ", flag: "🇬🇶" },
  { name: "Eritrea", code: "ER", flag: "🇪🇷" },
  { name: "Estonia", code: "EE", flag: "🇪🇪" },
  { name: "Eswatini", code: "SZ", flag: "🇸🇿" },
  { name: "Ethiopia", code: "ET", flag: "🇪🇹" },
  { name: "Falkland Islands (Malvinas)", code: "FK", flag: "🇫🇰" },
  { name: "Faroe Islands", code: "FO", flag: "🇫🇴" },
  { name: "Fiji", code: "FJ", flag: "🇫🇯" },
  { name: "Finland", code: "FI", flag: "🇫🇮" },
  { name: "France", code: "FR", flag: "🇫🇷" },
  { name: "French Guiana", code: "GF", flag: "🇬🇫" },
  { name: "French Polynesia", code: "PF", flag: "🇵🇫" },
  { name: "French Southern Territories", code: "TF", flag: "🇹🇫" },
  { name: "Gabon", code: "GA", flag: "🇬🇦" },
  { name: "Gambia", code: "GM", flag: "🇬🇲" },
  { name: "Georgia", code: "GE", flag: "🇬🇪" },
  { name: "Germany", code: "DE", flag: "🇩🇪" },
  { name: "Ghana", code: "GH", flag: "🇬🇭" },
  { name: "Gibraltar", code: "GI", flag: "🇬🇮" },
  { name: "Greece", code: "GR", flag: "🇬🇷" },
  { name: "Greenland", code: "GL", flag: "🇬🇱" },
  { name: "Grenada", code: "GD", flag: "🇬🇩" },
  { name: "Guadeloupe", code: "GP", flag: "🇬🇵" },
  { name: "Guam", code: "GU", flag: "🇬🇺" },
  { name: "Guatemala", code: "GT", flag: "🇬🇹" },
  { name: "Guernsey", code: "GG", flag: "🇬🇬" },
  { name: "Guinea", code: "GN", flag: "🇬🇳" },
  { name: "Guinea-Bissau", code: "GW", flag: "🇬🇼" },
  { name: "Guyana", code: "GY", flag: "🇬🇾" },
  { name: "Haiti", code: "HT", flag: "🇭🇹" },
  { name: "Heard Island and McDonald Islands", code: "HM", flag: "🇭🇲" },
  { name: "Holy See", code: "VA", flag: "🇻🇦" },
  { name: "Honduras", code: "HN", flag: "🇭🇳" },
  { name: "Hong Kong", code: "HK", flag: "🇭🇰" },
  { name: "Hungary", code: "HU", flag: "🇭🇺" },
  { name: "Iceland", code: "IS", flag: "🇮🇸" },
  { name: "India", code: "IN", flag: "🇮🇳" },
  { name: "Indonesia", code: "ID", flag: "🇮🇩" },
  { name: "Iran", code: "IR", flag: "🇮🇷" },
  { name: "Iraq", code: "IQ", flag: "🇮🇶" },
  { name: "Ireland", code: "IE", flag: "🇮🇪" },
  { name: "Isle of Man", code: "IM", flag: "🇮🇲" },
  { name: "Israel", code: "IL", flag: "🇮🇱" },
  { name: "Italy", code: "IT", flag: "🇮🇹" },
  { name: "Jamaica", code: "JM", flag: "🇯🇲" },
  { name: "Japan", code: "JP", flag: "🇯🇵" },
  { name: "Jersey", code: "JE", flag: "🇯🇪" },
  { name: "Jordan", code: "JO", flag: "🇯🇴" },
  { name: "Kazakhstan", code: "KZ", flag: "🇰🇿" },
  { name: "Kenya", code: "KE", flag: "🇰🇪" },
  { name: "Kiribati", code: "KI", flag: "🇰🇮" },
  { name: "Korea, Democratic People's Republic of", code: "KP", flag: "🇰🇵" },
  { name: "Korea, Republic of", code: "KR", flag: "🇰🇷" },
  { name: "Kosovo", code: "XK", flag: "🇽🇰" },
  { name: "Kuwait", code: "KW", flag: "🇰🇼" },
  { name: "Kyrgyzstan", code: "KG", flag: "🇰🇬" },
  { name: "Lao People's Democratic Republic", code: "LA", flag: "🇱🇦" },
  { name: "Latvia", code: "LV", flag: "🇱🇻" },
  { name: "Lebanon", code: "LB", flag: "🇱🇧" },
  { name: "Lesotho", code: "LS", flag: "🇱🇸" },
  { name: "Liberia", code: "LR", flag: "🇱🇷" },
  { name: "Libya", code: "LY", flag: "🇱🇾" },
  { name: "Liechtenstein", code: "LI", flag: "🇱🇮" },
  { name: "Lithuania", code: "LT", flag: "🇱🇹" },
  { name: "Luxembourg", code: "LU", flag: "🇱🇺" },
  { name: "Macao", code: "MO", flag: "🇲🇴" },
  { name: "Madagascar", code: "MG", flag: "🇲🇬" },
  { name: "Malawi", code: "MW", flag: "🇲🇼" },
  { name: "Malaysia", code: "MY", flag: "🇲🇾" },
  { name: "Maldives", code: "MV", flag: "🇲🇻" },
  { name: "Mali", code: "ML", flag: "🇲🇱" },
  { name: "Malta", code: "MT", flag: "🇲🇹" },
  { name: "Marshall Islands", code: "MH", flag: "🇲🇭" },
  { name: "Martinique", code: "MQ", flag: "🇲🇶" },
  { name: "Mauritania", code: "MR", flag: "🇲🇷" },
  { name: "Mauritius", code: "MU", flag: "🇲🇺" },
  { name: "Mayotte", code: "YT", flag: "🇾🇹" },
  { name: "Mexico", code: "MX", flag: "🇲🇽" },
  { name: "Micronesia, Federated States of", code: "FM", flag: "🇫🇲" },
  { name: "Moldova, Republic of", code: "MD", flag: "🇲🇩" },
  { name: "Monaco", code: "MC", flag: "🇲🇨" },
  { name: "Mongolia", code: "MN", flag: "🇲🇳" },
  { name: "Montenegro", code: "ME", flag: "🇲🇪" },
  { name: "Montserrat", code: "MS", flag: "🇲🇸" },
  { name: "Morocco", code: "MA", flag: "🇲🇦" },
  { name: "Mozambique", code: "MZ", flag: "🇲🇿" },
  { name: "Myanmar", code: "MM", flag: "🇲🇲" },
  { name: "Namibia", code: "NA", flag: "🇳🇦" },
  { name: "Nauru", code: "NR", flag: "🇳🇷" },
  { name: "Nepal", code: "NP", flag: "🇳🇵" },
  { name: "Netherlands", code: "NL", flag: "🇳🇱" },
  { name: "New Caledonia", code: "NC", flag: "🇳🇨" },
  { name: "New Zealand", code: "NZ", flag: "🇳🇿" },
  { name: "Nicaragua", code: "NI", flag: "🇳🇮" },
  { name: "Niger", code: "NE", flag: "🇳🇪" },
  { name: "Nigeria", code: "NG", flag: "🇳🇬" },
  { name: "Niue", code: "NU", flag: "🇳🇺" },
  { name: "Norfolk Island", code: "NF", flag: "🇳🇫" },
  { name: "North Macedonia", code: "MK", flag: "🇲🇰" },
  { name: "Northern Mariana Islands", code: "MP", flag: "🇲🇵" },
  { name: "Norway", code: "NO", flag: "🇳🇴" },
  { name: "Oman", code: "OM", flag: "🇴🇲" },
  { name: "Pakistan", code: "PK", flag: "🇵🇰" },
  { name: "Palau", code: "PW", flag: "🇵🇼" },
  { name: "Palestine, State of", code: "PS", flag: "🇵🇸" },
  { name: "Panama", code: "PA", flag: "🇵🇦" },
  { name: "Papua New Guinea", code: "PG", flag: "🇵🇬" },
  { name: "Paraguay", code: "PY", flag: "🇵🇾" },
  { name: "Peru", code: "PE", flag: "🇵🇪" },
  { name: "Philippines", code: "PH", flag: "🇵🇭" },
  { name: "Pitcairn", code: "PN", flag: "🇵🇳" },
  { name: "Poland", code: "PL", flag: "🇵🇱" },
  { name: "Portugal", code: "PT", flag: "🇵🇹" },
  { name: "Puerto Rico", code: "PR", flag: "🇵🇷" },
  { name: "Qatar", code: "QA", flag: "🇶🇦" },
  { name: "Romania", code: "RO", flag: "🇷🇴" },
  { name: "Russian Federation", code: "RU", flag: "🇷🇺" },
  { name: "Rwanda", code: "RW", flag: "🇷🇼" },
  { name: "Réunion", code: "RE", flag: "🇷🇪" },
  { name: "Saint Barthélemy", code: "BL", flag: "🇧🇱" },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    code: "SH",
    flag: "🇸🇭",
  },
  { name: "Saint Kitts and Nevis", code: "KN", flag: "🇰🇳" },
  { name: "Saint Lucia", code: "LC", flag: "🇱🇨" },
  { name: "Saint Martin (French part)", code: "MF", flag: "🇲🇫" },
  { name: "Saint Pierre and Miquelon", code: "PM", flag: "🇵🇲" },
  { name: "Saint Vincent and the Grenadines", code: "VC", flag: "🇻🇨" },
  { name: "Samoa", code: "WS", flag: "🇼🇸" },
  { name: "San Marino", code: "SM", flag: "🇸🇲" },
  { name: "Sao Tome and Principe", code: "ST", flag: "🇸🇹" },
  { name: "Saudi Arabia", code: "SA", flag: "🇸🇦" },
  { name: "Senegal", code: "SN", flag: "🇸🇳" },
  { name: "Serbia", code: "RS", flag: "🇷🇸" },
  { name: "Seychelles", code: "SC", flag: "🇸🇨" },
  { name: "Sierra Leone", code: "SL", flag: "🇸🇱" },
  { name: "Singapore", code: "SG", flag: "🇸🇬" },
  { name: "Sint Maarten (Dutch part)", code: "SX", flag: "🇸🇽" },
  { name: "Slovakia", code: "SK", flag: "🇸🇰" },
  { name: "Slovenia", code: "SI", flag: "🇸🇮" },
  { name: "Solomon Islands", code: "SB", flag: "🇸🇧" },
  { name: "Somalia", code: "SO", flag: "🇸🇴" },
  { name: "South Africa", code: "ZA", flag: "🇿🇦" },
  {
    name: "South Georgia and the South Sandwich Islands",
    code: "GS",
    flag: "🇬🇸",
  },
  { name: "South Sudan", code: "SS", flag: "🇸🇸" },
  { name: "Spain", code: "ES", flag: "🇪🇸" },
  { name: "Sri Lanka", code: "LK", flag: "🇱🇰" },
  { name: "Sudan", code: "SD", flag: "🇸🇩" },
  { name: "Suriname", code: "SR", flag: "🇸🇷" },
  { name: "Svalbard and Jan Mayen", code: "SJ", flag: "🇸🇯" },
  { name: "Sweden", code: "SE", flag: "🇸🇪" },
  { name: "Switzerland", code: "CH", flag: "🇨🇭" },
  { name: "Syrian Arab Republic", code: "SY", flag: "🇸🇾" },
  { name: "Taiwan", code: "TW", flag: "🇹🇼" },
  { name: "Tajikistan", code: "TJ", flag: "🇹🇯" },
  { name: "Tanzania, United Republic of", code: "TZ", flag: "🇹🇿" },
  { name: "Thailand", code: "TH", flag: "🇹🇭" },
  { name: "Timor-Leste", code: "TL", flag: "🇹🇱" },
  { name: "Togo", code: "TG", flag: "🇹🇬" },
  { name: "Tokelau", code: "TK", flag: "🇹🇰" },
  { name: "Tonga", code: "TO", flag: "🇹🇴" },
  { name: "Trinidad and Tobago", code: "TT", flag: "🇹🇹" },
  { name: "Tunisia", code: "TN", flag: "🇹🇳" },
  { name: "Turkey", code: "TR", flag: "🇹🇷" },
  { name: "Turkmenistan", code: "TM", flag: "🇹🇲" },
  { name: "Turks and Caicos Islands", code: "TC", flag: "🇹🇨" },
  { name: "Tuvalu", code: "TV", flag: "🇹🇻" },
  { name: "Uganda", code: "UG", flag: "🇺🇬" },
  { name: "Ukraine", code: "UA", flag: "🇺🇦" },
  { name: "United Arab Emirates", code: "AE", flag: "🇦🇪" },
  { name: "United Kingdom", code: "GB", flag: "🇬🇧" },
  { name: "United States", code: "US", flag: "🇺🇸" },
  { name: "United States Minor Outlying Islands", code: "UM", flag: "🇺🇲" },
  { name: "Uruguay", code: "UY", flag: "🇺🇾" },
  { name: "Uzbekistan", code: "UZ", flag: "🇺🇿" },
  { name: "Vanuatu", code: "VU", flag: "🇻🇺" },
  { name: "Venezuela", code: "VE", flag: "🇻🇪" },
  { name: "Viet Nam", code: "VN", flag: "🇻🇳" },
  { name: "Virgin Islands (U.S.)", code: "VI", flag: "🇻🇮" },
  { name: "Wallis and Futuna", code: "WF", flag: "🇼🇫" },
  { name: "Western Sahara", code: "EH", flag: "🇪🇭" },
  { name: "Yemen", code: "YE", flag: "🇾🇪" },
  { name: "Zambia", code: "ZM", flag: "🇿🇲" },
  { name: "Zimbabwe", code: "ZW", flag: "🇿🇼" },
  { name: "England", code: "GB-ENG", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { name: "Scotland", code: "GB-SCT", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { name: "Wales", code: "GB-WLS", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿" },
  { name: "Northern Ireland", code: "GB-NIR", flag: "🏴󠁧󠁢󠁮󠁩󠁲󠁿" },
];
export const timezones = [
  { name: "UTC-12:00 (Baker Island)", value: "UTC-12:00", flag: "🕐" },
  { name: "UTC-11:00 (American Samoa)", value: "UTC-11:00", flag: "🕐" },
  { name: "UTC-10:00 (Hawaii)", value: "UTC-10:00", flag: "🕐" },
  { name: "UTC-09:00 (Alaska)", value: "UTC-09:00", flag: "🕐" },
  { name: "UTC-08:00 (Pacific)", value: "UTC-08:00", flag: "🕐" },
  { name: "UTC-07:00 (Mountain)", value: "UTC-07:00", flag: "🕐" },
  { name: "UTC-06:00 (Central)", value: "UTC-06:00", flag: "🕐" },
  { name: "UTC-05:00 (Eastern)", value: "UTC-05:00", flag: "🕐" },
  { name: "UTC-04:00 (Atlantic)", value: "UTC-04:00", flag: "🕐" },
  { name: "UTC-03:00 (Argentina)", value: "UTC-03:00", flag: "🕐" },
  { name: "UTC-02:00 (Mid-Atlantic)", value: "UTC-02:00", flag: "🕐" },
  { name: "UTC-01:00 (Azores)", value: "UTC-01:00", flag: "🕐" },
  { name: "UTC+00:00 (London)", value: "UTC+00:00", flag: "🕐" },
  { name: "UTC+01:00 (Berlin)", value: "UTC+01:00", flag: "🕐" },
  { name: "UTC+02:00 (Cairo)", value: "UTC+02:00", flag: "🕐" },
  { name: "UTC+03:00 (Moscow)", value: "UTC+03:00", flag: "🕐" },
  { name: "UTC+04:00 (Dubai)", value: "UTC+04:00", flag: "🕐" },
  { name: "UTC+05:00 (Karachi)", value: "UTC+05:00", flag: "🕐" },
  { name: "UTC+05:30 (Mumbai)", value: "UTC+05:30", flag: "🕐" },
  { name: "UTC+06:00 (Dhaka)", value: "UTC+06:00", flag: "🕐" },
  { name: "UTC+07:00 (Bangkok)", value: "UTC+07:00", flag: "🕐" },
  { name: "UTC+08:00 (Beijing)", value: "UTC+08:00", flag: "🕐" },
  { name: "UTC+09:00 (Tokyo)", value: "UTC+09:00", flag: "🕐" },
  { name: "UTC+10:00 (Sydney)", value: "UTC+10:00", flag: "🕐" },
  { name: "UTC+11:00 (Solomon Islands)", value: "UTC+11:00", flag: "🕐" },
  { name: "UTC+12:00 (New Zealand)", value: "UTC+12:00", flag: "🕐" },
];

export const languages = [
  { name: "Afrikaans", flag: "🇿🇦", value: "AF" },
  { name: "Albanian", flag: "🇦🇱", value: "SQ" },
  { name: "Amharic", flag: "🇪🇹", value: "AM" },
  { name: "Arabic", flag: "🇸🇦", value: "AR" },
  { name: "Armenian", flag: "🇦🇲", value: "HY" },
  { name: "Assamese", flag: "🇮🇳", value: "AS" },
  { name: "Aymara", flag: "🇧🇴", value: "AY" },
  { name: "Azerbaijani", flag: "🇦🇿", value: "AZ" },
  { name: "Bengali", flag: "🇧🇩", value: "BN" },
  { name: "Bhojpuri", flag: "🇮🇳", value: "BH" },
  { name: "Bosnian", flag: "🇧🇦", value: "BS" },
  { name: "Bulgarian", flag: "🇧🇬", value: "BG" },
  { name: "Catalan", flag: "🇪🇸", value: "CA" },
  { name: "Cebuano", flag: "🇵🇭", value: "CEB" },
  { name: "Chewa", flag: "🇲🇼", value: "NY" },
  { name: "Chinese (Simplified)", flag: "🇨🇳", value: "ZH" },
  { name: "Chinese (Traditional)", flag: "🇨🇳", value: "ZH-TW" },
  { name: "Corsican", flag: "🇫🇷", value: "CO" },
  { name: "Croatian", flag: "🇭🇷", value: "HR" },
  { name: "Czech", flag: "🇨🇿", value: "CS" },
  { name: "Danish", flag: "🇩🇰", value: "DA" },
  { name: "Dhivehi", flag: "🇲🇻", value: "DV" },
  { name: "Dutch", flag: "🇳🇱", value: "NL" },
  { name: "English", flag: "🇬🇧", value: "EN" },
  { name: "Esperanto", flag: "🌐", value: "EO" },
  { name: "Estonian", flag: "🇪🇪", value: "ET" },
  { name: "Ewe", flag: "🇬🇭", value: "EE" },
  { name: "Filipino", flag: "🇵🇭", value: "TL" },
  { name: "Finnish", flag: "🇫🇮", value: "FI" },
  { name: "French", flag: "🇫🇷", value: "FR" },
  { name: "Frisian", flag: "🇳🇱", value: "FY" },
  { name: "Galician", flag: "🇪🇸", value: "GL" },
  { name: "Georgian", flag: "🇬🇪", value: "KA" },
  { name: "German", flag: "🇩🇪", value: "DE" },
  { name: "Greek", flag: "🇬🇷", value: "EL" },
  { name: "Gujarati", flag: "🇮🇳", value: "GU" },
  { name: "Haitian Creole", flag: "🇭🇹", value: "HT" },
  { name: "Hausa", flag: "🇳🇬", value: "HA" },
  { name: "Hawaiian", flag: "🇺🇸", value: "HAW" },
  { name: "Hebrew", flag: "🇮🇱", value: "HE" },
  { name: "Hindi", flag: "🇮🇳", value: "HI" },
  { name: "Hungarian", flag: "🇭🇺", value: "HU" },
  { name: "Icelandic", flag: "🇮🇸", value: "IS" },
  { name: "Igbo", flag: "🇳🇬", value: "IG" },
  { name: "Ilocano", flag: "🇵🇭", value: "ILO" },
  { name: "Indonesian", flag: "🇮🇩", value: "ID" },
  { name: "Irish", flag: "🇮🇪", value: "GA" },
  { name: "Italian", flag: "🇮🇹", value: "IT" },
  { name: "Japanese", flag: "🇯🇵", value: "JA" },
  { name: "Javanese", flag: "🇮🇩", value: "JV" },
  { name: "Kannada", flag: "🇮🇳", value: "KN" },
  { name: "Kazakh", flag: "🇰🇿", value: "KK" },
  { name: "Khmer", flag: "🇰🇭", value: "KM" },
  { name: "Kinyarwanda", flag: "🇷🇼", value: "RW" },
  { name: "Konkani", flag: "🇮🇳", value: "KOK" },
  { name: "Korean", flag: "🇰🇷", value: "KO" },
  { name: "Kurdish (Kurmanji)", flag: "🇹🇷", value: "KU" },
  { name: "Kurdish (Sorani)", flag: "🇮🇶", value: "CKB" },
  { name: "Kyrgyz", flag: "🇰🇬", value: "KY" },
  { name: "Lao", flag: "🇱🇦", value: "LO" },
  { name: "Latin", flag: "🌐", value: "LA" },
  { name: "Latvian", flag: "🇱🇻", value: "LV" },
  { name: "Lingala", flag: "🇨🇩", value: "LN" },
  { name: "Lithuanian", flag: "🇱🇹", value: "LT" },
  { name: "Luganda", flag: "🇺🇬", value: "LG" },
  { name: "Luxembourgish", flag: "🇱🇺", value: "LB" },
  { name: "Macedonian", flag: "🇲🇰", value: "MK" },
  { name: "Maithili", flag: "🇮🇳", value: "MAI" },
  { name: "Malagasy", flag: "🇲🇬", value: "MG" },
  { name: "Malay", flag: "🇲🇾", value: "MS" },
  { name: "Malayalam", flag: "🇮🇳", value: "ML" },
  { name: "Maltese", flag: "🇲🇹", value: "MT" },
  { name: "Maori", flag: "🇳🇿", value: "MI" },
  { name: "Marathi", flag: "🇮🇳", value: "MR" },
  { name: "Meiteilon (Manipuri)", flag: "🇮🇳", value: "MNI" },
  { name: "Mongolian", flag: "🇲🇳", value: "MN" },
  { name: "Myanmar (Burmese)", flag: "🇲🇲", value: "MY" },
  { name: "Nepali", flag: "🇳🇵", value: "NE" },
  { name: "Norwegian", flag: "🇳🇴", value: "NO" },
  { name: "Odia (Oriya)", flag: "🇮🇳", value: "OR" },
  { name: "Oromo", flag: "🇪🇹", value: "OM" },
  { name: "Pashto", flag: "🇦🇫", value: "PS" },
  { name: "Persian", flag: "🇮🇷", value: "FA" },
  { name: "Polish", flag: "🇵🇱", value: "PL" },
  { name: "Portuguese", flag: "🇵🇹", value: "PT" },
  { name: "Punjabi", flag: "🇮🇳", value: "PA" },
  { name: "Quechua", flag: "🇵🇪", value: "QU" },
  { name: "Romanian", flag: "🇷🇴", value: "RO" },
  { name: "Russian", flag: "🇷🇺", value: "RU" },
  { name: "Samoan", flag: "🇼🇸", value: "SM" },
  { name: "Sanskrit", flag: "🇮🇳", value: "SA" },
  { name: "Scots Gaelic", flag: "🇬🇧", value: "GD" },
  { name: "Sepedi", flag: "🇿🇦", value: "NSP" },
  { name: "Serbian", flag: "🇷🇸", value: "SR" },
  { name: "Sesotho", flag: "🇿🇦", value: "ST" },
  { name: "Shona", flag: "🇿🇼", value: "SN" },
  { name: "Sindhi", flag: "🇵🇰", value: "SD" },
  { name: "Sinhala", flag: "🇱🇰", value: "SI" },
  { name: "Slovak", flag: "🇸🇰", value: "SK" },
  { name: "Slovenian", flag: "🇸🇮", value: "SL" },
  { name: "Somali", flag: "🇸🇴", value: "SO" },
  { name: "Spanish", flag: "🇪🇸", value: "ES" },
  { name: "Sundanese", flag: "🇮🇩", value: "SU" },
  { name: "Swahili", flag: "🇹🇿", value: "SW" },
  { name: "Swedish", flag: "🇸🇪", value: "SV" },
  { name: "Tajik", flag: "🇹🇯", value: "TG" },
  { name: "Tamil", flag: "🇮🇳", value: "TA" },
  { name: "Tatar", flag: "🇷🇺", value: "TT" },
  { name: "Telugu", flag: "🇮🇳", value: "TE" },
  { name: "Thai", flag: "🇹🇭", value: "TH" },
  { name: "Tigrinya", flag: "🇪🇷", value: "TI" },
  { name: "Tsonga", flag: "🇿🇦", value: "TS" },
  { name: "Turkish", flag: "🇹🇷", value: "TR" },
  { name: "Turkmen", flag: "🇹🇲", value: "TK" },
  { name: "Twi", flag: "🇬🇭", value: "TW" },
  { name: "Ukrainian", flag: "🇺🇦", value: "UK" },
  { name: "Urdu", flag: "🇵🇰", value: "UR" },
  { name: "Uyghur", flag: "🇨🇳", value: "UG" },
  { name: "Uzbek", flag: "🇺🇿", value: "UZ" },
  { name: "Vietnamese", flag: "🇻🇳", value: "VI" },
  { name: "Welsh", flag: "🇬🇧", value: "CY" },
  { name: "Xhosa", flag: "🇿🇦", value: "XH" },
  { name: "Yiddish", flag: "🇮🇱", value: "YI" },
  { name: "Yoruba", flag: "🇳🇬", value: "YO" },
  { name: "Zulu", flag: "🇿🇦", value: "ZU" },
];
